#alias
alias la='ls -la'
alias ..='cd ../'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi='vim'
